In [10]:
import pandas as pd
import plotly.express as px
import os
import re
import datetime as time
import jovian
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
import emoji
import re
from collections import Counter
from wordcloud import WordCloud, STOPWORDS

In [20]:
filePath = r'C:\Users\Emily\Downloads\WhatsApp\_chat.txt'
df = pd.read_fwf(filePath, header = None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6548 entries, 0 to 6547
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6548 non-null   object
 1   1       36 non-null     object
 2   2       34 non-null     object
 3   3       29 non-null     object
 4   4       27 non-null     object
 5   5       20 non-null     object
 6   6       20 non-null     object
 7   7       18 non-null     object
 8   8       17 non-null     object
 9   9       14 non-null     object
dtypes: object(10)
memory usage: 511.7+ KB

In [21]:
nonNulls = df[~df.isnull().any(axis=1)]
nonNulls

,0,1,2,3,4,5,6,7,8,9
65,This will make you chuckle .. JAX and Ricardo ...,to,bring,her,keys,to,open,the,door,!!
278,"[29/06/2018, 17:59:34] Mum: Thank you so much ...",t,riend,an,the,d,ing,ome,food,sh
473,"[15/07/2018, 11:59:20] Emily Wade: Going for p...","e,",and a,so,ess,ik,ly t,th,ow u,h
639,"[22/09/2018, 20:47:21] Mum: Mum is feeling so ...",..,so sh,kn,w th,y,ere,her,...,sh
823,"[18/11/2018, 19:43:52] Dad: Oi wades ..... mum...",t,is th,n w,can,bo,k a,oli,ay .,..
1669,"[22/05/2019, 07:56:10] Dad: Double trouble tod...",qu,stion,tw,ce e,en,if y,u t,ink,ou
2285,"[01/09/2019, 19:36:40] Emily Wade: Tryna sort ...",o,rains,tha,lat,.,.. a,pre,iate,Mu
2544,"According to the research, Plymouth is officia...",a,d onl,ne,earc,i,tere,t i,“fr,en
2594,https://www.tui.co.uk/destinations/caribbean/j...,LS,z9hzL,jMg,YS_d,_K,feFl,cCP,c58C,Xc
2702,"[05/12/2019, 20:10:56] Dad: You missed an even...",m,m rui,ed,er ‘,or,on b,eu’,cred,nt
3241,"[07/06/2020, 10:42:23] Emily Wade: Morning all...",d.,It’s,ot,ome,u,eful,lin,s at,th
4083,"[07/02/2021, 00:00:07] Emily Wade: Pls wake me...",’m,out o,be,pls,an,tha,ks,nd s,rr
5308,"[29/12/2021, 17:10:34] Emily Wade: Arrived saf...",W,NDERF,L X,as f,ll,of h,ppi,"ess,",lo